project:
  type: website
  output-dir: docs

website:
  title: "Our Research"
  navbar:
    right:
      - about.qmd
      - icon: file-earmark-person-fill
        href: https://shaokang-yang.github.io/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

plugins:
    - search: {}
    - encryptcontent: {}

